version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/ANPR_VERCEL
permissions:
  - object: /home/ubuntu/ANPR_VERCEL
    pattern: "**"
    owner: ubuntu
    group: ubuntu
hooks:
  BeforeInstall:
    - location: before_install.sh
      timeout: 300
      runas: ubuntu
  AfterInstall:
    - location: start_services.sh
      timeout: 300
      runas: ubuntu
    - location: app_operations.sh
      timeout: 300
      runas: ubuntu