version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - echo Installing dependencies...
      - sudo apt-get update
      - sudo apt-get install -y python3-pip
      - pip3 install -r requirements.txt
  pre_build:
    commands:
      - echo Pre-build phase...
      - git clone https://github.com/TrideepNandi/ANPR_VERCEL.git /home/ubuntu/ANPR_VERCEL
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Django app...
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
  discard-paths: yes