version: 0.1

environment_variables:
  plaintext:
    DJANGO_SETTINGS_MODULE: ANPR_VERCEL.settings
    SECRET_KEY: 'django-insecure-l@r-v5cbi12wk(x3mu_c0_(k&i35tej@w&mt)kgotmy==gp9a^'
    DATABASE_DEFAULT_URL: postgresql_psycopg2://ANPRDBMasterUser:TnandiRootUser@anpr-db.c586e4goez87.ap-south-1.rds.amazonaws.com:1782/postgres
    EMAIL_HOST_USER: 'nandi.trideep2003@gmail.com'
    EMAIL_HOST_PASSWORD: 'frue ulyt bzxe zbjy'
    ANPR_DB_INSTANCE_USER: 'ANPRDBMasterUser'
    ANPR_DB_INSTANCE_PASSWORD: 'TnandiRootUser'
    ANPR_DB_INSTANCE_HOST: 'anpr-db.c586e4goez87.ap-south-1.rds.amazonaws.com'
    ANPR_DB_INSTANCE_PORT: '1782'

phases:
  pre_build:
    commands:
      - echo Prebuild ops
      - pip3 install -r requirements.txt
  build:
    commands:
      - echo Building the application 
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
