version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - echo Installing dependencies...
      - sudo apt-get update
      - sudo apt-get install -y python3-pip
      - pip3 install virtualenv

  pre_build:
    commands:
      - echo Copying scripts and configuration files...

  build:
    commands:
      - echo Building application...
      - virtualenv /tmp/env
      - source /tmp/env/bin/activate
      - pip install -r requirements.txt

  post_build:
    commands:
      - echo Changing permissions for scripts and configuration files...

artifacts:
  files:
    - '**/*'
